"""Hyperparameters of the algorithm."""

INIT_INDIVIDUALS = 5
GENERATIONS = 1000
CURR_GENERATION = 0
OFFSPRING = 20
DIE_INDIVIDUALS = 0
DISCARD_PERCENT = 0.1
MUTATATION_PROB = 0.1
DISCARD_PERCENT = 0.2
TUPLE_SIZE = 3
STEP = 200
